# Generated by Django 6.0.3 on 2026-03-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='clases',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
