# Generated by Django 6.0.3 on 2026-03-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_profesor_clases'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
