# Generated by Django 6.0.3 on 2026-04-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'administrador'), ('profesor', 'Profesor'), ('estudiante', 'Estudiante')], max_length=20),
        ),
    ]
